kitty_mod        ctrl+shift

map              cmd+t              new_tab_with_cwd
map              cmd+shift+t        close_tab
map              cmd+alt+left       previous_tab
map              cmd+alt+right      next_tab

map              cmd+d              new_window_with_cwd
map              cmd+shift+d        close_window
map              cmd+ctrl+left      previous_window
map              cmd+ctrl+right     next_window
