# include       ./themes/kanso.conf
# include        ./themes/xcodedark.conf
include         ./themes/tokyonight.conf
# include        ./themes/gruvbox.conf

include         ./tabs/_index.conf
# include        ./tabs/arctic.conf
# include        ./tabs/catpuccin.conf
# include        ./tabs/dusk.conf
include         ./tabs/tokyonight.conf
# include        ./tabs/gruvbox.conf
# include        ./tabs/rose-pine.conf

include         ./keys.conf
include         ./cursor.conf
include         ./layout.conf
include         ./font.conf

