tab_bar_edge                    bottom
tab_bar_style                   powerline
tab_powerline_style             round
tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"
tab_title_max_length            20
active_tab_font_style           bold
inactive_tab_font_style         normal
tab_bar_min_tabs                1
tab_bar_margin_height           4.0 4.0
tab_font_size                   13.0
macos_menubar_title_max_length  20
macos_titlebar_color            background
