#

background                #14171d
foreground                #C5C9C7

active_border_color       #292a30
inactive_border_color     #53606e
bell_border_color         #e0af68

selection_background      #22262D
selection_foreground      #C5C9C7

color0                    #14171d
color1                    #c4746e
color2                    #8a9a7b
color3                    #c4b28a
color4                    #8ba4b0
color5                    #a292a3
color6                    #8ea4a2
color7                    #C8C093
color8                    #A4A7A4
color9                    #E46876
color10                   #87a987
color11                   #E6C384
color12                   #7FB4CA
color13                   #938AA9
color14                   #7AA89F
color15                   #C5C9C7

