# https://github.com/arzg/vim-colors-xcode

background                #292a30
foreground                #dfdfe0

active_border_color       #292a30
inactive_border_color     #53606e
bell_border_color         #e0af68

selection_foreground      #53606e
selection_background      #393b44

color0                    #292a30
color1                    #ff8170
color2                    #78c2b3
color3                    #ffa14f
color4                    #4eb0cc
color5                    #b281eb
color6                    #84b360
color7                    #a3b1bf
color8                    #53606e
color9                    #ff7ab2
color10                   #acf2e4
color11                   #d9c97c
color12                   #6bdfff
color13                   #dabaff
color14                   #b0e687
color15                   #53606e

