"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 2000

format = """
$directory $git_branch$git_status$cmd_duration
$character"""

[directory]
format = "[$path]($style)"
style = "blue"
truncate_to_repo = true
truncation_length = 0
read_only = "🔒"

[git_branch]
format = "[$branch]($style)"
style = "242"

[git_status]
modified = "[*](218)"
stashed = "[≡](cyan)"
ahead = "[⇡](cyan)"
diverged = "[⇡⇣](cyan)"
behind = "[⇣](cyan)"
format = '([$modified $ahead_behind]($style))'

[cmd_duration]
min_time = 1000
format = "[$duration]($style)"
style = "yellow"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)"
